### ISSUE TITLE
exchange-scrapers: OKEx is broken

### ISSUE THREAD

**Issue by frranck** [diadata-org/diadata#131]
**Describe the bug**
seems OKEx is receiving wrong values and can't parse trades

**To Reproduce**

run 
go run cmd/exchange-scrapers/collectorTextOnly/scraper.go -exchange OKEx

trades are not showing up and error message:
WARN[0001] reconnect the scraping to ws, invalid character 'M' looking for beginning of value:[]

**Comment by PumpkingWok** [comment]
Hi @frranck,
I have just seen this issue, i have implemented OKEx scraper.I had to include a function to ping manually the websocket every tot seconds. Maybe there is a issue regard it, i'm going to test it.

**Comment by PumpkingWok** [comment]
Ok, i think that i have found the problem, OKEx now compresses the data traveling on websocket.
It is a demo developed by OKEx (there is a go code example too)
https://github.com/okcoin-okex/API-docs-OKEx.com/tree/master/demo
Ask me without problems if you want an help with this issue.
Have a nice day !!
