### ISSUE TITLE
Defi Lending Rate Scraper for Bancor

### ISSUE THREAD

**Issue by wubswurld** [diadata-org/diadata#259]
Your job is to source and connect the <NAME> lending protocol, sourcing lending rates, volume, and other data, pushing it into our database for open-source usage.

Task: Source primary data defined below for connectivity to our database for:

- Lending Rate
- DeFi Total Value Locked (USD)
- Biggest Protocol/Dominance % of total
- Total Value Locked (24H in USD; ETH; BTC)
- Total ETH locked
- Underlying Blockchain
- Most locked asset
- Protocol token (if applicable)

Please commit a scraper which ideally also scrapes historical data as much as possible.
Tutorial on data format: https://docs.diadata.org/documentation/tutorials/write-your-own-defi-lending-rate-scraper

In case you need to extend the data model, you should also include it into your commit.

A concrete similar example on the data set to source https://defipulse.com/.

**Comment by jppade** [comment]
@wubswurld Hi, we already posted this issue a couple of days ago. As Bancor protocol V2 is announced and expected to be there very soon. As long as it isn't there, we put the issue on hold but expect to activate it on gitcoin soon.
