### ISSUE TITLE
No llegan los DAI comprados a mi metamask

### ISSUE THREAD

**Issue by marcosrin** [diadata-org/diadata#274]
Compré DAI y no llegaron a mi metamask . Habrá forma de solucionarlo. Gracias

**Comment by kaythxbye** [comment]
Did you add them as custom tokens? In Metamask go to "Assets" -> "Add Token" -> "Custom Token" and use 0x84cA8bc7997272c7CfB4D0Cd3D55cd942B3c9419 for our address.

If this doesn't work please contact us in our support channel on Telegram: https://t.me/DIAdata_org
