### ISSUE TITLE
x_0.1

### ISSUE THREAD

**Issue by yusa24** [diadata-org/diadata#287]
We are looking for a developer that can provide a scraper for trading data from the <NAME> protocol.
The scraper must be written in Go and work concurrently and efficiently. You should adapt to our underlying data structures. For information on implementation details, please have a look at:

https://docs.diadata.org/documentation/tutorials/exchangescrapers

Please commit a scraper which ideally also scrapes historical data as much as possible.

**Comment by kaythxbye** [comment]
Do you have a specific data source you wish to fund?
