### ISSUE TITLE
No Reciept of Airdrop DIA 

### ISSUE THREAD

**Issue by cb362271** [diadata-org/diadata#363]
I followed guidelines (held DIA throughout October and provided liquidity on Uniswap for a short period), and was thus expecting some DIA from the airdrop supposedly distributed on January 11th. However, I have not received a single DIA. I can give my wallet address that corresponds with my activity in a more private venue if necessary, but I'm curious why I haven't received any tokens yet.

**Comment by kaythxbye** [comment]
Hi, please contact airdrop-support@diadata.org with your wallet address for this issue.

**Comment by cb362271** [comment]
Thank you for your response
