### ISSUE TITLE
DIA Staking Return

### ISSUE THREAD

**Issue by Huitzilli** [diadata-org/diadata#374]
1. When I will be getting all my DIA that I staked back ?
.
ETH address: 0xe891FcfbA41d10a53Bf40a5412F1787D4327AEE4
.
2. I only received 23.102 DIA tokens so far. Is this all the DIA tokens that I will be getting ?
.
Email: chessmasterdiaz@gmail.com
.
Thank you so much for taking the time to answer my questions.

**Comment by kaythxbye** [comment]
followup by email, closed
