### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by montanaflynn** [diadata-org/diadata#49]
Adding a scraper I found https://docs.diadata.org/exchange-scrapers.html to be lacking. 

Additionally the README.md has no information on how to run the project, where to find documentation or what is expected from the scrapers.

**Comment by kaythxbye** [comment]
Hi @montanaflynn, good point, I will take care of it to update the docu.

**Comment by kaythxbye** [comment]
Fixed, new documentation is at https://docs.diadata.org
