### ISSUE TITLE
Add all pairs from exchanges

### ISSUE THREAD

**Issue by montanaflynn** [diadata-org/diadata#52]
I noticed some exchanges are not scraping all the available pairs.

For example the most recent exchange gate.io (https://github.com/diadata-org/api-golang/pull/47) only captures a small subset of [the available pairs](https://data.gate.io/api2/1/pairs).

Instead of manually adding them to the `exchange-scrapers.json` file it's probably better to automate this using any available APIs such as the one linked above.

**Comment by PumpkingWok** [comment]
Hi @montanaflynn,
I usually add a small subset (max 30 pairs) to `exchange-scrapers.json` for avoiding to increase too much the file in line for easy editing in the future if necessary. I agree with you that maybe it is better to automate the pairs population via request API, or at least choose from the two scenarios before run the scraper.

**Comment by montanaflynn** [comment]
@PumpkingWok is that documented anywhere? Just pick random 30? I was looking for a specific token I know is traded on gate and didn't find it which is what led me to create this issue.

**Comment by frranck** [comment]
Hi @montanaflynn very good point, we need to add some pairs discovery into the APIScraper interface

**Comment by frranck** [comment]
Ok so we would need a pair discovery service, that would fetch all available pairs for each exchange and store it in redis.

**Comment by kaythxbye** [comment]
Closing, continues in #87
