### ISSUE TITLE
ETH/EUR CME Future / Algorithm & Oracle

### ISSUE THREAD

**Issue by diamw** [diadata-org/diadata#6]
Develop ETH/EUR algorithm and oracle, based on availible DIA database, that is matching the CME future ETH price the closest https://www.cmegroup.com/trading/cryptocurrency-indices/cf-ethereum-reference-rate.html 

+ Use existing ECB reference data for EUR/USD rate on database (https://github.com/diadata-org/api-golang/blob/master/exchange-scrapers/scrapers/ECBScraper.go) 
+ Add Documentation
+ Add Oracle, updating the price after ECB publishing (4pm CET) daily.

**Comment by PumpkingWok** [comment]
Hi @diamw,
Are you still interested on this issue ? If yes, i would like to ask some questions regard it.
Thanks.

**Comment by mestorlx** [comment]
@frranck Are you still interested in this implementation?

**Comment by frranck** [comment]
We are developing the oracle part in house ATM, but we will still need the CME wrapper, we will publish a bounty for it next month.

**Comment by kaythxbye** [comment]
Closed due to age.
