### ISSUE TITLE
Write a Trades Scraper for BKEX Exchange

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#636]
We are looking for a developer that can provide a scraper for trading data from BKEX exchange:
https://www.bkex.com/

The scraper must be written in Go and work concurrently and efficiently. Furthermore, you must use the websocket API in order to get trading data:
https://bkexapi.github.io/docs/api_en.htm?shell#websocket

Feel free to substitute the existing Bittrex scraper in our codebase:
https://github.com/diadata-org/diadata/blob/master/pkg/dia/scraper/exchange-scrapers/BittrexScraper.go

Finally, please adapt to our underlying data structures. For information on implementation details, please have a look at:
https://docs.diadata.org/documentation/tutorials/exchangescrapers

**Comment by top1st** [comment]
@jppade 
https://github.com/diadata-org/diadata/pull/640
