### ISSUE TITLE
Write a Trades Scraper for Orca DEX on Solana

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#645]
We are looking for a Go developer who is experienced in writing applications interfacing with Solana blockchain.
Your task is to write a trades scraper for Orca DEX on Solana:
https://www.orca.so/

The data must be fetched directly from on-chain. For the contracts and the structure of the DEX, have a look at the documentation:
https://docs.orca.so/orca-for-builders/orca-developer-portal

In order to connect to Solana blockchain you can use the following node:
https://solana-api.projectserum.com

Furthermore, you should adhere to our underlying architecture / data structures. For instructions please go to:
https://docs.diadata.org/documentation/tutorials/exchangescrapers

Feel free to also have a look at our existing exchange scrapers at:
https://github.com/diadata-org/diadata/tree/master/pkg/dia/scraper/exchange-scrapers

In case you have questions don't hesitate to ask!

**Comment by alexjorgef** [comment]
Never interact with the Solana network but I'm excited to do it, can start working on this.

**Comment by jppade** [comment]
Hi @alexjorgef , thanks for your interest. That's great! Feel free to apply on DeWork as well:
https://app.dework.xyz/dia-dao/techinical-guild-l4naw7xj?taskId=1607a4d9-9d2b-4e4c-a271-8e3c9c2e4a6a
