### ISSUE TITLE
Fix Serum Asset Collector

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#651]
Our Serum asset collector is supposed to fetch assets traded on Serum DEX:
https://github.com/diadata-org/diadata/blob/master/pkg/dia/service/assetservice/source/serum.go
The task consists in fixing the scraper which is failing currently. More precisely, the method `getTokenNames()` is returning an empty struct:
https://github.com/diadata-org/diadata/blob/master/pkg/dia/service/assetservice/source/serum.go#L136

**Comment by Grivn** [comment]
I think I've resolved it in pull request 654 (https://github.com/diadata-org/diadata/pull/654). Please help to review it. Thank you!

**Comment by jppade** [comment]
Hi @Grivn 
you are absolutely right! The code is working. So it turns out it was the various nodes we were testing it with that did not do the job. Feel free to head over to DeWork and claim the task.
Many thanks for this contribution. Looking forward to the next ones!
