### ISSUE TITLE
Write a Trades Scraper for Bitstamp Exchange

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#677]
We are looking for a developer that can provide a scraper for trading data from Bitstamp exchange:
https://www.bitstamp.net/

The scraper must be written in Go and work concurrently and efficiently. Furthermore, you must use the websocket API in order to get trading data:
https://www.bitstamp.net/websocket/v2/

Finally, please adapt to our underlying data structures. For information on implementation details, please have a look at:
https://docs.diadata.org/documentation/tutorials/exchangescrapers

**Comment by mul1sh** [comment]
@jppade is this still open? I can get it sorted in a day or less.

Here is my [gitcoin profile](https://gitcoin.co/mul1sh) showcasing my expertise, thanks
