### ISSUE TITLE
Write an NFT Trades Scraper for blur.io Marketplace

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#698]
We are looking for a Go developer who is experienced in writing applications interfacing with the Ethereum blockchain. Basic knowledge in NFTs is helpful but not necessary.
Your task is to write a scraper for the trades on the blur.io marketplaceV1
https://etherscan.io/address/0x000000000000ad05ccc4f10045630fb830b95127

The structure for the scraper is already laid out. More precisely, you should create the file 
github.com/diadata-org/diadata/pkg/dia/nftTrade-scrapers/blurV1.go
and implement the scraping logic therein.
A Go binding of the underlying contract is located in 
github.com/diadata-org/diadata/config/nftContracts/blurv1

The scraper should be incremental, i.e. it should start scraping at the contract's deploy block and take up scraping at whichever block it stopped. As an example you can have a look at the Opensea trades scraper here:
[github.com/diadata-org/diadata/pkg/dia/nftTrade-scrapers/opensea.go]https://github.com/diadata-org/diadata/blob/master/pkg/dia/nft/nftTrade-scrapers/opensea.go
 
Furthermore, please also take into account that NFT classes and NFTs which are not in our DB yet should be added in the trades scraper, similar to lines 476 and 481 in the Opensea trades scraper.

If you have questions don't hesitate to ask. Ideally we can connect on our Discord server in order to discuss if necessary.

**Comment by naftalimurgor** [comment]
Hey @jppade 

I'm interested in  taking on this one. I'll apply via Gitcoin

Thanks!

**Comment by hp4eth** [comment]
Hi @jppade, I noticed that no one is working on this bounty. Wondering if I can work on it, I have experience in both Go and reading the Ethereum logs. Tried to apply on Gitcoin but the "Express Interest" button is not visible.

**Comment by jppade** [comment]
Hey @hp4eth , thanks for your interest. Unfortunately, the bounty has already been completed. We'd be happy to see you on upcoming bounties though!

**Comment by hp4eth** [comment]
Hi @jppade, I just applied to the Oracle monitoring bounty, I'm writing just to say I would love to work on that bounty. I’m planning on creating a Docker Compose file that includes services for TimescaleDB and the monitoring app. I’ll use Go-Ethereum to get the logs and will use goroutines and Go channels to monitor multiple blockchains in parallel. Also, will create unit tests and documentation in the oracle-monitoring repository. Looking forward to work with you!

**Comment by jppade** [comment]
Hey @hp4eth , sorry again. The Oracle monitoring bounty had already been assigned on DeWork a week ago.

**Comment by hp4eth** [comment]
that's ok, I'll wait for the next one on Gitcoin! 
Bests
