### ISSUE TITLE
Parse TokenExchangeUnderlying event from Curve.Finance contracts

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#741]
We are looking for a Go developer who is very familiar with the Curve.Finance DEX contracts.
More precisely, pools from certain registries emit not only `TokenExchange` events, but also `TokenExchangeUnderlying` events.
In the current version of our scraper
https://github.com/diadata-org/diadata/blob/master/pkg/dia/scraper/exchange-scrapers/CurvefiScraper.go
the way decimals for an Exchange's In- and Out- amounts are determined only prove to be valid for for some pools (see line 432 ff.).
The task consists in finding a general approach to read the decimals corresponding to the given amounts from on-chain.

As a (counter-)example please have a look at the `TokenExchangeUnderlying` event log in the following transaction:
https://etherscan.io/tx/0xc01defc69eb9571edeaeaf8da31a8512b3ddbf8b01d5299a40b04203f7977a24#eventlog
Here, the scraper finds `sold_id=2` refers to the underlying asset USDC as read from the corresponding registry contract for the pool:
https://etherscan.io/address/0xB9fC157394Af804a3578134A6585C0dc9cc990d4#readContract
As USDC has 6 decimals and USDP has  18 decimals, the scraper finds that roughly 39221 PAX Dollars have been bought for around 38237553686576274 USDC, which is obviously wrong.

Please test your implementation thoroughly by running the scraper for some time.
More information on how to run a scraper locally can be obtained here:
https://docs.diadata.org/contribute/tutorials/exchangescrapers#steps-to-run-a-scraper-locally

**Comment by jppade** [comment]
Hi @developerfred , thanks for your interest. I think this is a misunderstanding, i.e. the situation is a bit more complex. Our scraper does not always expect 6 decimals for stablecoins (It finds 18 decimals for PAX Dollar for instance). Instead, it looks for the decimals of the underlying tokens by calling underlying_coins on the pool address in the corresponding pool registry. However, it turns out that the implementation of these pools varies. Hence, one has to look closer into the pool contracts - or find another workaround.
So all that just to say: Be warned. This is (most probably) not a straightforward one and hence advertised for someone who is expert in Curve contracts.

**Comment by developerfred** [comment]
Got it, I'm going to explore curve contracts
