### ISSUE TITLE
Write a Google Finance Forex Scraper

### ISSUE THREAD

**Issue by jppade** [diadata-org/diadata#746]
The task consists in fetching Forex quotations from Google Finance. The scraper must be written in Go and adhere to our data structures. In particular, it should be implemented as a foreign scraper.
Furthermore, the data should be fetched using google sheets, delivering quotations for the following Fiat assets:
TZS,TRY,NGN,MXN,BRL,ZAR,RUB,ARS,AED,TWD,EUR,JPY,GBP,AUD,NZD,CAD,SEK,CHF,PHP,HUF,CNY,HKD,SGD,INR,IDR,THB,MYR
Preferably, the scraper is implemented with a ticker and looks for new quotations with a given ticker frequency.

**Comment by alexjorgef** [comment]
With a dummy scraper, extracting data from the Google Finance page led to some issues regarding cookie renovation. I will investigate further what can be done
