### ISSUE TITLE
FilterMA not ignoring Trade out of order

### ISSUE THREAD

**Issue by mestorlx** [diadata-org/diadata#78]
In `func (s *FilterMA) compute(trade dia.Trade)` if the trade timestamp is older than `s.lastTrade` should be ignored. In the following test the error message `FilterMA: Ignoring Trade out of order` is shown however the values are being used on the average computation which mean it is not ignored.

```
func TestFilterMaIgnore(t *testing.T) {

	filterParam := 10
	firstPrice := 50.0

	d := time.Date(2016, time.August, 15, 0, 0, 0, 0, time.UTC)
	f := NewFilterMA("XRP", "", d, filterParam)
	steps := filterParam
	p := firstPrice
	priceIncrements := 1.0
	for i := 0; i <= steps; i++ {
		f.compute(dia.Trade{EstimatedUSDPrice: p, Time: d})
		d = d.Add(-time.Second)
		p += priceIncrements
	}
	f.finalComputeEndOfBlock(d)
	v := f.filterPointForBlock()
	if v.Value != firstPrice {
		t.Errorf("error should be initial value:%f got:%f", firstPrice, v.Value)
	}
}
```

**Comment by mestorlx** [comment]
If this bug is confirmed I think I can provide a solution. Just let me know and I can submit a PR

**Comment by frranck** [comment]
@mestorlx This cannot happen since orders are ordered by the trade block service. Indeed you're right we should explicitly ignore them here too.

**Comment by frranck** [comment]
Or maybe once for all filters in the filter service?

**Comment by mestorlx** [comment]
@frranck I think the mechanism is inside the filter already.
Let me submit a PR with a quick fix.
